//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input System/BaseControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BaseControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BaseControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BaseControls"",
    ""maps"": [
        {
            ""name"": ""FPS"",
            ""id"": ""1a54d1de-c15c-4ed9-991b-a8c81fce9f51"",
            ""actions"": [
                {
                    ""name"": ""MouseAim"",
                    ""type"": ""Value"",
                    ""id"": ""43ea719e-1aae-4bad-962a-1d023fa14e65"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""2d341490-146b-4df9-a344-fa7b58dfb2cd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""502e439f-32c3-40eb-8b61-8fc37f1ed1b4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6094d323-6601-4779-993e-acbaac89712a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""c5092640-ae06-45e2-a935-42386757cba4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""f92e637f-3419-4869-99d6-29a2febbc2d9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter Map View"",
                    ""type"": ""Button"",
                    ""id"": ""e8e5ecc9-3dfa-4e82-8b25-fc4628201215"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExecuteGoCode"",
                    ""type"": ""Button"",
                    ""id"": ""0eece59a-5c7b-4d32-a3e1-8c1767e543e3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectAiTeammate"",
                    ""type"": ""Button"",
                    ""id"": ""40f9a28e-f576-4d63-94ec-c6cc6c12fa3f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectAbility"",
                    ""type"": ""Button"",
                    ""id"": ""3b296281-1ee3-48f1-b9fd-80bd8dfcbca2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectAiGroup"",
                    ""type"": ""Button"",
                    ""id"": ""d3b3e711-fdef-4c50-a060-b77ad5118881"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InstantCommand"",
                    ""type"": ""Button"",
                    ""id"": ""0d01fa37-a12c-44dd-b229-b27572df0120"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QueueCommand"",
                    ""type"": ""Button"",
                    ""id"": ""61764266-7c38-4d32-a6ae-cb1f11649306"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""697dac52-eb3b-469c-8723-f63e170b5a37"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""3050750a-8bae-4ee2-8964-b4a1ebd8ce4f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem"",
                    ""type"": ""Button"",
                    ""id"": ""f35539ce-dfc1-4c00-96ee-5e65c9ff1ffc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a34adc38-ee59-4432-8a53-2c88c5cd1e3c"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""2311d57e-d30d-4680-8053-83b572ebc0d6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4b20df2a-3ebb-4f18-b124-192e7b059fee"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""aa547c87-ce79-4001-8e50-6c9fe5c7ad34"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9c191c05-42fd-475c-bd7d-9cc8039b5877"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""48ba05b8-d3ee-423a-83e7-f3b0ddf15c49"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""749be40c-2162-4f36-9550-438125b21c79"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acdb7e5d-44a2-4512-aa64-b9f723bec898"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31489799-60b7-4657-a940-aaad598600d1"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ad014cf-41d6-475e-85a5-467cc3152b64"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68199d2b-3830-47d3-8e3c-3b9644b8b4ef"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExecuteGoCode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""461ff661-10f5-4450-9365-7a58d09add7d"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter Map View"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57de4f69-f0a8-4d08-b3c5-b1db8d20c8bf"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiTeammate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90823a19-a4ab-456c-ae1c-d2bed7411773"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiTeammate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f43a9d0a-dbe7-462a-88ba-2ff2bc7daabc"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiTeammate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52a05500-96c7-413e-9caf-f685c6798fe3"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiTeammate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d0abdfe-cc3b-43f2-a9cc-c9badb6ab6e2"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiTeammate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94fa14ff-7ee0-4139-9383-f5e9b3d57780"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cca92ac-300b-4029-9417-97612a45d0be"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""146251cf-88e4-4908-b268-9c54dd1fd9c2"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d66fd7b3-1325-4a97-b56a-47a8e5016fd0"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""23ecb2e4-d4e2-4a24-8c6d-7d0a15cabbed"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4f25e74b-2b0d-465f-a2bf-d9cacf6dea83"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""ce11e8b0-1f81-4db7-8be3-1987cc903149"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""d6155b68-cd9c-4c5e-9971-ff62ce5970b8"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""f1423446-8922-449a-883f-fbe165b02073"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""a149b2c9-9c58-4c16-88cb-df506b295d55"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""dbf66bf3-e9aa-49a0-99ad-deea8da98b65"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""0e65add2-b728-4639-9948-804d4440c6e8"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""e1c0597c-0c24-4391-b893-fbef44b8bd0c"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""a7ba112a-be4a-46d7-a91f-3173bd0eecb6"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""3547bb65-77b3-4c40-bae9-75e123df189f"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""38c03fe9-0f04-4083-acba-eb3a6d0afe0a"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""c8b9aa91-27cf-421d-9e4a-6850f1c97386"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""9a938b6c-19c7-4572-97d1-2f5af46b67d9"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""bdcbe6b9-4733-40f9-918a-0388d4c7bd31"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c8eb29f2-e41c-4925-b54f-ada98a469ec4"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InstantCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8ffe19d-b5f9-481a-aa36-397272cd0715"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InstantCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Move"",
                    ""id"": ""403494cb-9a8d-4f2f-8a5d-75ce29eb9ce6"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueCommand"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""92aa28b1-1f68-4c56-b1a6-0ebe9e784b31"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""3ed92fa6-7137-4f23-af7a-0cb06933ca4f"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Look"",
                    ""id"": ""e80f91bf-e1cf-465e-91d4-a6812b85d3d0"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueCommand"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""06dce185-2368-44f0-bdd3-b69d0c266109"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""23ab45ff-f058-416c-88a2-91e01d97872b"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a169b277-af31-4f86-a8aa-d76c0905ca3a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8192ff1c-a5b5-410f-824a-37034c96b514"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cdc77c9-d098-403b-bd8f-ab0bed4ad9f1"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MapView"",
            ""id"": ""e44b057d-1423-4714-b6e2-59ad010a238c"",
            ""actions"": [
                {
                    ""name"": ""MapMove"",
                    ""type"": ""Value"",
                    ""id"": ""3e993dc4-7e8d-4302-9e48-00b34b0ebc66"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Exit Map"",
                    ""type"": ""Button"",
                    ""id"": ""d7420f82-f022-49ba-88f9-2c238ab6e90b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExecuteGoCode"",
                    ""type"": ""Button"",
                    ""id"": ""c4d7fa1a-5bf7-4bc4-a0f6-6811ee4775a3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectAiTeammate"",
                    ""type"": ""Button"",
                    ""id"": ""8dbd0ccd-1074-4975-a009-4c84359eb878"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectAiGroup"",
                    ""type"": ""Button"",
                    ""id"": ""751973ba-1781-4149-a534-ab41cccb8f67"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InstantCommand"",
                    ""type"": ""Button"",
                    ""id"": ""f4ded500-8968-4792-8335-cc16360f1d34"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QueueCommand"",
                    ""type"": ""Button"",
                    ""id"": ""8ae06d28-5947-4554-b6c0-6fd5bc5b32ea"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""6de1c244-4066-4911-95c5-928f20b60700"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MapMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""900d6919-a1f5-478a-a4e8-7aa66e67fc07"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MapMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3f6f9572-3f78-4850-b3f2-566fec7466f9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MapMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""49526737-fba9-430e-9e7b-6860d8a03232"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MapMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""69be0d55-c758-4ed8-8989-b89d0a741aa6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MapMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e586ac30-84b2-4e75-944a-665e4923930e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExecuteGoCode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a150be76-9895-4c6b-9288-348073466c74"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiTeammate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""235b6422-1cf7-4050-ad5a-45bdb8486cc0"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiTeammate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87b20197-0797-45e4-abd7-e537faecc183"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiTeammate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc9f8bf3-356a-4908-b024-3d4def7ef1d8"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiTeammate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74466e53-bac4-464a-bd2b-04395c403d0e"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiTeammate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""7453fa51-a198-4707-9ef2-ee1752d32c3f"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""de9880fb-b54c-4c0e-829f-1a7cfa6821c3"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5726dd8d-c0d8-482a-b97c-8879d4e52496"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""7806be1d-1ba3-40cd-9802-a189297eb163"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""16a52693-4fb1-4ff3-b979-7386421e5b01"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""bb8c63a2-51ad-4ce4-99c1-c85a7cd287d5"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""778d1280-3ea4-4cf4-89ab-bfb70df0738f"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4262080a-da38-4fd4-9e07-0672ceea6589"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""79945e18-7711-4c17-bb5c-f08e83f55048"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""7e88171a-042d-413f-b37b-0ffe2f58d38c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7668d8d6-8587-4aa5-aa55-b5ac5bc6404b"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""1a341efc-546e-4e64-bb1b-690e6b3071ee"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""2cdb4e52-e300-429a-89c2-ad0b18bdc3ff"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""76e48e31-3040-4b8f-a1ac-ce018a64985b"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""49019904-3118-4574-9525-7e0008afb2c0"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAiGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Move"",
                    ""id"": ""4fa5bc65-9559-4cf7-933c-d766aedfefe9"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueCommand"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a7a1b60a-e421-40bb-9493-d3a71f6d7297"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""e0d30f1e-46c8-4c94-9432-182115f40213"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Look"",
                    ""id"": ""e3f6c568-b453-4530-8834-8f56b39f3df6"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueCommand"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""704b1401-30e7-44db-8456-3927c1133e5f"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""ae926e21-6b02-47b4-9727-d497acd63064"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QueueCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""249b6a4e-ea8c-4fc1-a9fe-ee811c1c0752"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InstantCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2448f24-7c73-422a-8330-12ac7ee4a0ef"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InstantCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c89dfede-ad25-43c4-b8c8-2df783249ac0"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // FPS
        m_FPS = asset.FindActionMap("FPS", throwIfNotFound: true);
        m_FPS_MouseAim = m_FPS.FindAction("MouseAim", throwIfNotFound: true);
        m_FPS_Move = m_FPS.FindAction("Move", throwIfNotFound: true);
        m_FPS_Sprint = m_FPS.FindAction("Sprint", throwIfNotFound: true);
        m_FPS_Jump = m_FPS.FindAction("Jump", throwIfNotFound: true);
        m_FPS_Crouch = m_FPS.FindAction("Crouch", throwIfNotFound: true);
        m_FPS_Interact = m_FPS.FindAction("Interact", throwIfNotFound: true);
        m_FPS_EnterMapView = m_FPS.FindAction("Enter Map View", throwIfNotFound: true);
        m_FPS_ExecuteGoCode = m_FPS.FindAction("ExecuteGoCode", throwIfNotFound: true);
        m_FPS_SelectAiTeammate = m_FPS.FindAction("SelectAiTeammate", throwIfNotFound: true);
        m_FPS_SelectAbility = m_FPS.FindAction("SelectAbility", throwIfNotFound: true);
        m_FPS_SelectAiGroup = m_FPS.FindAction("SelectAiGroup", throwIfNotFound: true);
        m_FPS_InstantCommand = m_FPS.FindAction("InstantCommand", throwIfNotFound: true);
        m_FPS_QueueCommand = m_FPS.FindAction("QueueCommand", throwIfNotFound: true);
        m_FPS_Fire = m_FPS.FindAction("Fire", throwIfNotFound: true);
        m_FPS_Reload = m_FPS.FindAction("Reload", throwIfNotFound: true);
        m_FPS_UseItem = m_FPS.FindAction("UseItem", throwIfNotFound: true);
        // MapView
        m_MapView = asset.FindActionMap("MapView", throwIfNotFound: true);
        m_MapView_MapMove = m_MapView.FindAction("MapMove", throwIfNotFound: true);
        m_MapView_ExitMap = m_MapView.FindAction("Exit Map", throwIfNotFound: true);
        m_MapView_ExecuteGoCode = m_MapView.FindAction("ExecuteGoCode", throwIfNotFound: true);
        m_MapView_SelectAiTeammate = m_MapView.FindAction("SelectAiTeammate", throwIfNotFound: true);
        m_MapView_SelectAiGroup = m_MapView.FindAction("SelectAiGroup", throwIfNotFound: true);
        m_MapView_InstantCommand = m_MapView.FindAction("InstantCommand", throwIfNotFound: true);
        m_MapView_QueueCommand = m_MapView.FindAction("QueueCommand", throwIfNotFound: true);
    }

    ~@BaseControls()
    {
        UnityEngine.Debug.Assert(!m_FPS.enabled, "This will cause a leak and performance issues, BaseControls.FPS.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_MapView.enabled, "This will cause a leak and performance issues, BaseControls.MapView.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FPS
    private readonly InputActionMap m_FPS;
    private List<IFPSActions> m_FPSActionsCallbackInterfaces = new List<IFPSActions>();
    private readonly InputAction m_FPS_MouseAim;
    private readonly InputAction m_FPS_Move;
    private readonly InputAction m_FPS_Sprint;
    private readonly InputAction m_FPS_Jump;
    private readonly InputAction m_FPS_Crouch;
    private readonly InputAction m_FPS_Interact;
    private readonly InputAction m_FPS_EnterMapView;
    private readonly InputAction m_FPS_ExecuteGoCode;
    private readonly InputAction m_FPS_SelectAiTeammate;
    private readonly InputAction m_FPS_SelectAbility;
    private readonly InputAction m_FPS_SelectAiGroup;
    private readonly InputAction m_FPS_InstantCommand;
    private readonly InputAction m_FPS_QueueCommand;
    private readonly InputAction m_FPS_Fire;
    private readonly InputAction m_FPS_Reload;
    private readonly InputAction m_FPS_UseItem;
    public struct FPSActions
    {
        private @BaseControls m_Wrapper;
        public FPSActions(@BaseControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseAim => m_Wrapper.m_FPS_MouseAim;
        public InputAction @Move => m_Wrapper.m_FPS_Move;
        public InputAction @Sprint => m_Wrapper.m_FPS_Sprint;
        public InputAction @Jump => m_Wrapper.m_FPS_Jump;
        public InputAction @Crouch => m_Wrapper.m_FPS_Crouch;
        public InputAction @Interact => m_Wrapper.m_FPS_Interact;
        public InputAction @EnterMapView => m_Wrapper.m_FPS_EnterMapView;
        public InputAction @ExecuteGoCode => m_Wrapper.m_FPS_ExecuteGoCode;
        public InputAction @SelectAiTeammate => m_Wrapper.m_FPS_SelectAiTeammate;
        public InputAction @SelectAbility => m_Wrapper.m_FPS_SelectAbility;
        public InputAction @SelectAiGroup => m_Wrapper.m_FPS_SelectAiGroup;
        public InputAction @InstantCommand => m_Wrapper.m_FPS_InstantCommand;
        public InputAction @QueueCommand => m_Wrapper.m_FPS_QueueCommand;
        public InputAction @Fire => m_Wrapper.m_FPS_Fire;
        public InputAction @Reload => m_Wrapper.m_FPS_Reload;
        public InputAction @UseItem => m_Wrapper.m_FPS_UseItem;
        public InputActionMap Get() { return m_Wrapper.m_FPS; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FPSActions set) { return set.Get(); }
        public void AddCallbacks(IFPSActions instance)
        {
            if (instance == null || m_Wrapper.m_FPSActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FPSActionsCallbackInterfaces.Add(instance);
            @MouseAim.started += instance.OnMouseAim;
            @MouseAim.performed += instance.OnMouseAim;
            @MouseAim.canceled += instance.OnMouseAim;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @EnterMapView.started += instance.OnEnterMapView;
            @EnterMapView.performed += instance.OnEnterMapView;
            @EnterMapView.canceled += instance.OnEnterMapView;
            @ExecuteGoCode.started += instance.OnExecuteGoCode;
            @ExecuteGoCode.performed += instance.OnExecuteGoCode;
            @ExecuteGoCode.canceled += instance.OnExecuteGoCode;
            @SelectAiTeammate.started += instance.OnSelectAiTeammate;
            @SelectAiTeammate.performed += instance.OnSelectAiTeammate;
            @SelectAiTeammate.canceled += instance.OnSelectAiTeammate;
            @SelectAbility.started += instance.OnSelectAbility;
            @SelectAbility.performed += instance.OnSelectAbility;
            @SelectAbility.canceled += instance.OnSelectAbility;
            @SelectAiGroup.started += instance.OnSelectAiGroup;
            @SelectAiGroup.performed += instance.OnSelectAiGroup;
            @SelectAiGroup.canceled += instance.OnSelectAiGroup;
            @InstantCommand.started += instance.OnInstantCommand;
            @InstantCommand.performed += instance.OnInstantCommand;
            @InstantCommand.canceled += instance.OnInstantCommand;
            @QueueCommand.started += instance.OnQueueCommand;
            @QueueCommand.performed += instance.OnQueueCommand;
            @QueueCommand.canceled += instance.OnQueueCommand;
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
            @UseItem.started += instance.OnUseItem;
            @UseItem.performed += instance.OnUseItem;
            @UseItem.canceled += instance.OnUseItem;
        }

        private void UnregisterCallbacks(IFPSActions instance)
        {
            @MouseAim.started -= instance.OnMouseAim;
            @MouseAim.performed -= instance.OnMouseAim;
            @MouseAim.canceled -= instance.OnMouseAim;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @EnterMapView.started -= instance.OnEnterMapView;
            @EnterMapView.performed -= instance.OnEnterMapView;
            @EnterMapView.canceled -= instance.OnEnterMapView;
            @ExecuteGoCode.started -= instance.OnExecuteGoCode;
            @ExecuteGoCode.performed -= instance.OnExecuteGoCode;
            @ExecuteGoCode.canceled -= instance.OnExecuteGoCode;
            @SelectAiTeammate.started -= instance.OnSelectAiTeammate;
            @SelectAiTeammate.performed -= instance.OnSelectAiTeammate;
            @SelectAiTeammate.canceled -= instance.OnSelectAiTeammate;
            @SelectAbility.started -= instance.OnSelectAbility;
            @SelectAbility.performed -= instance.OnSelectAbility;
            @SelectAbility.canceled -= instance.OnSelectAbility;
            @SelectAiGroup.started -= instance.OnSelectAiGroup;
            @SelectAiGroup.performed -= instance.OnSelectAiGroup;
            @SelectAiGroup.canceled -= instance.OnSelectAiGroup;
            @InstantCommand.started -= instance.OnInstantCommand;
            @InstantCommand.performed -= instance.OnInstantCommand;
            @InstantCommand.canceled -= instance.OnInstantCommand;
            @QueueCommand.started -= instance.OnQueueCommand;
            @QueueCommand.performed -= instance.OnQueueCommand;
            @QueueCommand.canceled -= instance.OnQueueCommand;
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
            @UseItem.started -= instance.OnUseItem;
            @UseItem.performed -= instance.OnUseItem;
            @UseItem.canceled -= instance.OnUseItem;
        }

        public void RemoveCallbacks(IFPSActions instance)
        {
            if (m_Wrapper.m_FPSActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFPSActions instance)
        {
            foreach (var item in m_Wrapper.m_FPSActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FPSActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FPSActions @FPS => new FPSActions(this);

    // MapView
    private readonly InputActionMap m_MapView;
    private List<IMapViewActions> m_MapViewActionsCallbackInterfaces = new List<IMapViewActions>();
    private readonly InputAction m_MapView_MapMove;
    private readonly InputAction m_MapView_ExitMap;
    private readonly InputAction m_MapView_ExecuteGoCode;
    private readonly InputAction m_MapView_SelectAiTeammate;
    private readonly InputAction m_MapView_SelectAiGroup;
    private readonly InputAction m_MapView_InstantCommand;
    private readonly InputAction m_MapView_QueueCommand;
    public struct MapViewActions
    {
        private @BaseControls m_Wrapper;
        public MapViewActions(@BaseControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MapMove => m_Wrapper.m_MapView_MapMove;
        public InputAction @ExitMap => m_Wrapper.m_MapView_ExitMap;
        public InputAction @ExecuteGoCode => m_Wrapper.m_MapView_ExecuteGoCode;
        public InputAction @SelectAiTeammate => m_Wrapper.m_MapView_SelectAiTeammate;
        public InputAction @SelectAiGroup => m_Wrapper.m_MapView_SelectAiGroup;
        public InputAction @InstantCommand => m_Wrapper.m_MapView_InstantCommand;
        public InputAction @QueueCommand => m_Wrapper.m_MapView_QueueCommand;
        public InputActionMap Get() { return m_Wrapper.m_MapView; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MapViewActions set) { return set.Get(); }
        public void AddCallbacks(IMapViewActions instance)
        {
            if (instance == null || m_Wrapper.m_MapViewActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MapViewActionsCallbackInterfaces.Add(instance);
            @MapMove.started += instance.OnMapMove;
            @MapMove.performed += instance.OnMapMove;
            @MapMove.canceled += instance.OnMapMove;
            @ExitMap.started += instance.OnExitMap;
            @ExitMap.performed += instance.OnExitMap;
            @ExitMap.canceled += instance.OnExitMap;
            @ExecuteGoCode.started += instance.OnExecuteGoCode;
            @ExecuteGoCode.performed += instance.OnExecuteGoCode;
            @ExecuteGoCode.canceled += instance.OnExecuteGoCode;
            @SelectAiTeammate.started += instance.OnSelectAiTeammate;
            @SelectAiTeammate.performed += instance.OnSelectAiTeammate;
            @SelectAiTeammate.canceled += instance.OnSelectAiTeammate;
            @SelectAiGroup.started += instance.OnSelectAiGroup;
            @SelectAiGroup.performed += instance.OnSelectAiGroup;
            @SelectAiGroup.canceled += instance.OnSelectAiGroup;
            @InstantCommand.started += instance.OnInstantCommand;
            @InstantCommand.performed += instance.OnInstantCommand;
            @InstantCommand.canceled += instance.OnInstantCommand;
            @QueueCommand.started += instance.OnQueueCommand;
            @QueueCommand.performed += instance.OnQueueCommand;
            @QueueCommand.canceled += instance.OnQueueCommand;
        }

        private void UnregisterCallbacks(IMapViewActions instance)
        {
            @MapMove.started -= instance.OnMapMove;
            @MapMove.performed -= instance.OnMapMove;
            @MapMove.canceled -= instance.OnMapMove;
            @ExitMap.started -= instance.OnExitMap;
            @ExitMap.performed -= instance.OnExitMap;
            @ExitMap.canceled -= instance.OnExitMap;
            @ExecuteGoCode.started -= instance.OnExecuteGoCode;
            @ExecuteGoCode.performed -= instance.OnExecuteGoCode;
            @ExecuteGoCode.canceled -= instance.OnExecuteGoCode;
            @SelectAiTeammate.started -= instance.OnSelectAiTeammate;
            @SelectAiTeammate.performed -= instance.OnSelectAiTeammate;
            @SelectAiTeammate.canceled -= instance.OnSelectAiTeammate;
            @SelectAiGroup.started -= instance.OnSelectAiGroup;
            @SelectAiGroup.performed -= instance.OnSelectAiGroup;
            @SelectAiGroup.canceled -= instance.OnSelectAiGroup;
            @InstantCommand.started -= instance.OnInstantCommand;
            @InstantCommand.performed -= instance.OnInstantCommand;
            @InstantCommand.canceled -= instance.OnInstantCommand;
            @QueueCommand.started -= instance.OnQueueCommand;
            @QueueCommand.performed -= instance.OnQueueCommand;
            @QueueCommand.canceled -= instance.OnQueueCommand;
        }

        public void RemoveCallbacks(IMapViewActions instance)
        {
            if (m_Wrapper.m_MapViewActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMapViewActions instance)
        {
            foreach (var item in m_Wrapper.m_MapViewActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MapViewActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MapViewActions @MapView => new MapViewActions(this);
    public interface IFPSActions
    {
        void OnMouseAim(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnEnterMapView(InputAction.CallbackContext context);
        void OnExecuteGoCode(InputAction.CallbackContext context);
        void OnSelectAiTeammate(InputAction.CallbackContext context);
        void OnSelectAbility(InputAction.CallbackContext context);
        void OnSelectAiGroup(InputAction.CallbackContext context);
        void OnInstantCommand(InputAction.CallbackContext context);
        void OnQueueCommand(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnUseItem(InputAction.CallbackContext context);
    }
    public interface IMapViewActions
    {
        void OnMapMove(InputAction.CallbackContext context);
        void OnExitMap(InputAction.CallbackContext context);
        void OnExecuteGoCode(InputAction.CallbackContext context);
        void OnSelectAiTeammate(InputAction.CallbackContext context);
        void OnSelectAiGroup(InputAction.CallbackContext context);
        void OnInstantCommand(InputAction.CallbackContext context);
        void OnQueueCommand(InputAction.CallbackContext context);
    }
}
